name: autotrader
dependencies:
    - python=3.8
    - pip=20.3.3
    - black=19.10b0
    - pytest=6.2.2
    - pip:
        - discord.py==1.6.0
        - google-cloud-storage==1.35.0
        - tda-api==1.1.5
        - coverage==5.4
        - selenium==3.141.0
